### ISSUE TITLE
build for Intel 19 (19.0.5)

### ISSUE THREAD

**Issue by gibbsp** [JCSDA-internal/jedi-stack-old#124]
Maintain environment modules on S4

Tasks:

- [x] build for Intel 19 (19.0.5)
    - [x] Intel MPI
- [x] update versions of modules as appropriate
- [x] test against ufo and fv3 bundles

Done:

- [x] modules as per Tasks are built
- [x] test as per Tasks pass with new modules built
    - [x] ufo
    - [x] fv3

```
export OPT=/data/users/rgrubin/opt/modules
module use -a $OPT/modulefiles/core
module load jedi/intel19-impi
```

The modulefile `jedi/intel19-impi` loads module `license_intel`, which is required for invoking the compiler.

---- 

Example test results:

**_ufo_**
100% tests passed, 0 tests failed out of 764

Subproject Time Summary:
eckit    = 139.89 sec*proc (115 tests)
fckit    = 244.92 sec*proc (14 tests)
gsw      =   0.28 sec*proc (2 tests)
ioda     =   9.73 sec*proc (17 tests)
oops     = 104.90 sec*proc (167 tests)
saber    = 2197.93 sec*proc (149 tests)
ufo      =  78.49 sec*proc (167 tests)

Label Time Summary:
atlas            = 120.28 sec*proc (133 tests)
download_data    =  11.45 sec*proc (2 tests)
executable       = 252.41 sec*proc (359 tests)
fortran          =   8.76 sec*proc (36 tests)
mpi              = 2046.19 sec*proc (116 tests)
openmp           = 2201.77 sec*proc (123 tests)
script           = 2391.36 sec*proc (401 tests)

Total Test time (real) = 2900.75 sec

**_fv3_**
100% tests passed, 0 tests failed out of 105

Label Time Summary:
fv3-jedi    = 4923.80 sec*proc (104 tests)
fv3jedi     = 4929.28 sec*proc (105 tests)
mpi         = 4917.81 sec*proc (73 tests)
script      = 4929.28 sec*proc (105 tests)

**Comment by mmiesch** [comment]
@gibbsp - what is the issue here?  To my knowledge, jedi builds fine with intel 19.0.5 - we use it often.

**Comment by mmiesch** [comment]
Issue moved to [JCSDA-internal/jedi-stack #24](https://github.com/JCSDA-internal/jedi-stack/issues/24) via [**ZenHub**](https://www.zenhub.com/)
