### ISSUE TITLE
Upgrade jedi stack on hera before release

### ISSUE THREAD

**Issue by rhoneyager** [JCSDA-internal/jedi-stack-old#141]
New C++14-compatible stacks are being built on hera. This issue tracks the progress of the stack build.

To load a stack:
```
export JEDI_OPT=/scratch1/NCEPDEV/jcsda/Ryan.Honeyager/jedi-stack/opt
module use $JEDI_OPT/modulefiles/core
module use $JEDI_OPT/modulefiles/apps
module load jedi/intel-18-impi-18    # Or use any of the stacks in the "apps" directory (listed below)
```

## Built Base Stacks (tested through ufo-bundle):
- [x] Intel 18 - jedi/intel-18-impi-18 - intel/18.0.5.274 with impi 2018 (jedi-impi/2018.4.274). This is the default stack.
- [x] Intel 19 - jedi/intel-19-impi-18 - intel/19.0.5.281 with impi 2018 (jedi-impi/2018.4.274).
- [x] Intel 20 - jedi/intel-20-impi-18 - intel/2020.2 with impi 2018 (jedi-impi/2018.4.274).

#### Stack component versions:
- boost headers 1.68.0
- bufrlib 11.3.2. @aerorahul I am matching the jedi-stack-provided version here. If you prefer a different source, let me know.
- ecbuild jcsda-3.3.2.jcsda3. See below.
- eckit jcsda-1.11.6.jcsda2. See below.
- eigen 3.3.7
- gsl_lite 0.34.0
- HDF5 1.12.0. This version is required for ioda-engines integration.
- nccmp 1.8.7.0
- netcdf 4.7.4
- pnetcdf 1.12.1
- pybind11 2.5.0
- szip 2.1.1
- zlib 1.2.11

#### Sysadmin-provided:
- cmake 3.16.1 - sysadmin-provided
- udunits

## Questions before proceeding:
- [ ] Which MPI stacks should be targeted (@aerorahul)? I am matching impi 2018 because it is the system default. We also have impi 2019 and 2020 as options. I have no problems with mix-and-match.
- [ ] How strongly do we want a gcc 9 stack on Hera? I experimented with this build and encountered a problem compiling HDF5 1.12.
- [ ] ECMWF dependencies: ecbuild, eckit, fckit, and atlas:
    - These can be provided either in the stack or in the bundle. Currently, fv3-bundle and ufo-bundle always build the "release-stable" branches of atlas, eckit, and fckit. How do we want to standardize this? Should these components be in both stack and bundle, bundle-only or stack-only? @mmiesch?
- [ ] Which optional dependencies do we want?
    - I expect at least cgal, gptl, nco, sqlite, json-validators.
    - [ ] If you want more, please leave comments.
    - [ ] @mmiesch Do we have PRs for the json-validation components?

#### Other issues:
- [ ] Test a bundle build with Intel 18 and C++14. (The current jedi codes have partial support for C++14. We need to test features that are unavailable in the base glibc, like std::make_unique.)
    - [ ] Generate a script in jedi-cmake that sets the correct compiler flags for this type of build.

**Comment by rhoneyager** [comment]
Stack ```jedi-stack-beta/intel-impi-18.0.5``` progress:

- [x] cmake (3.18.2)
- [x] szip (2.1.1)
- [x] hdf5 (1.12.0; parallel mode; szip compression turned on)
- [x] pnetcdf (1.12.1)
- [x] udunits (2.2.27.6)
- [x] netcdf-c (4.7.4; parallel mode; byte i/o enabled; szip enabled)
- [x] netcdf-fortran (4.5.4)
- [x] nccmp (1.8.6.5)
- [x] eigen3 (3.3.7)
- [ ] boost headers (1.74.0; in progress)
- [ ] eckit
- [ ] fckit
- [ ] atlas
- [ ] bufrlib
- [ ] Microsoft GSL
- [ ] pybind11
- [ ] ...

**Comment by mmiesch** [comment]
> @mmiesch Do we have PRs for the json-validation components?

They have already been merged - the jedi-stack has an option to build these.  New containers with json-validation have been generated today and are about to be deployed for CI

**Comment by mmiesch** [comment]
> How do we want to standardize this? Should these components be in both stack and bundle, bundle-only or stack-only? @mmiesch?

Our preferred mode of operation is to use the most recent tags in modules but use release-stable in bundles.  Merges into release-stable are associated with tags so these should be the same.  But, loading a module called `release-stable` is not very informative because it doesn't tell users what is in it or when it was built.

That said, we want to see if we can get jedi to work with the ecmwf release branches.  We've made progress with this but it's not quite working yet.

**Comment by mmiesch** [comment]
And...to address your other question, we typically install ecbuild and eckit in modules and build fckit and atlas as part of the bundle.  We could move toward providing all these in the modules but maybe that should wait until after the release.

**Comment by aerorahul** [comment]
@rhoneyager 
bufr library version 11.4.0 from https://github.com/NOAA-EMC/NCEPLIBS-bufr
Intel 2018 and 2020 stacks should suffice.  GNU stacks on HPC's don't make sense to me.
eckit release-stable at a minimum.  fckit and atlas would be nice too.  atlas takes a while to compile, each time someone clones and builds a bundle.

**Comment by mmiesch** [comment]
Issue moved to [JCSDA-internal/jedi-stack #27](https://github.com/JCSDA-internal/jedi-stack/issues/27) via [**ZenHub**](https://www.zenhub.com/)
