### ISSUE TITLE
Intel 18, C++14 and eckit

### ISSUE THREAD

**Issue by rhoneyager** [JCSDA-internal/jedi-stack-old#142]
@mmiesch When you rebuilt eckit, did you encounter any issues with building eckit::SQLSelect?

Compiler fails on this block of code with parameter ```ownedOutputs```:
```
SQLSelect::SQLSelect(const Expressions& columns, const std::vector<std::reference_wrapper<const SQLTable>>& tables,
                     std::shared_ptr<SQLExpression> where, SQLOutput& output,
                     std::vector<std::unique_ptr<SQLOutput>>&& ownedOutputs) :
    select_(columns),
    where_(where),
    simplifiedWhere_(0),
    ownedOutputs_(std::move(ownedOutputs)),
    ...
```

Somehow, Intel 18 is deciding to copy the vector instead of moving it, which is illegal, and then the compiler dies with an error.

Affects #141 and #125.

**Comment by mmiesch** [comment]
I have not seen this before but which version of eckit are you using?  1.11.6.jcsda2 includes an sql-related bugfix from @markjolah

**Comment by rhoneyager** [comment]
Also on 1.11.6.jcsda2. Temporarily disabling SQL, since I don't think we use it.

I've got one other error: JCSDA/eckit#17. eckit successfully builds after patching this.

**Comment by mmiesch** [comment]
Thanks - this is ok as a kluge for Hera now but I hesitate to merge it until we at least check what they think upstream.  We have already applied 3 patched to ecbuild and 2 patched to eckit and I worry that our forks are starting to diverge again.  This is not needed for the intel builds on half a dozen other systems so is it something peculiar about intel 18/gcc combo on Hera?

**Comment by markjolah** [comment]
@rhoneyager I think you are going to need an older version of GCC or a newer version of Intel or you will have a host of un-debuggable ABI violations.   This will be the first of many.  Looking over the intel version 18 support, the latest version of GCC they have qualified with in gcc-6.3.  This means gcc-6.5.0 should be used if possible.  Note gcc-6+ will give you full [GCC C++14 support](https://gcc.gnu.org/projects/cxx-status.html#cxx14).  With intel 19 or 20 you can use gcc-8.4 series.  And with intel 20 you can use gcc-9.3 series.

**Comment by markjolah** [comment]
I also think when you downgrade the GCC you should be able to get the MS gsl library to work.

**Comment by mmiesch** [comment]
official release notes aside, I have found no problems with the intel 19 - gcc 9 combo on several platforms.  I think this is what I use on AWS, Discover, and Cheyenne.  S4 is intel 20 / gcc 8.3.0.    Let me know if you want to try installing gcc/g++ from source and are having problems with it.  There is that capability in jedi-stack but if that doesn't work I can also check how nvidia's hpc-container-maker does it.

**Comment by mmiesch** [comment]
Oh - you can do it with spack too, right?  That might be easiest.

**Comment by rhoneyager** [comment]
I have a ticket open with the Hera sysadmins, so that they can install gcc 6. They are concerned that they might also need to reinstall / retarget Intel 18's compiler, and I don't think that they need to do something that drastic (i.e. the rest of NOAA uses that installation).

Spack still has that mirror-use bug, and it is firewalled so that it is only usable by the sysadmins.


Intel 18 is NOAA's standard compiler for Hera, and I was told that supporting it is a priority.

However... further down the stack build, Intel 18 completely choked on Atlas. In C++14 mode with gcc 9, it *really* dislikes rvalue moves of vectors of unique_ptrs. I hope that this is more a bug on the gcc side rather than on Intel.

**Comment by mmiesch** [comment]
Good plan - if you convince them that their intel 18 is not functioning properly - i.e. cannot handle c++-14 - because of the insufficient gnu support, they might be motivated to install gcc 6.  I don't think that concern is warranted in my experience.  They do not have to change the default gcc - only provide an installation in a separate directory, either as a module or as a stand-alone.  Either would work.  I've gotten this to work on 4 other HPC systems now and there was no need to touch the existing intel compiler installation.

**Comment by mmiesch** [comment]
Issue moved to [JCSDA-internal/jedi-stack #29](https://github.com/JCSDA-internal/jedi-stack/issues/29) via [**ZenHub**](https://www.zenhub.com/)
