### ISSUE TITLE
FMS: check for GNU v10.x Fortran and update FFLAGS

### ISSUE THREAD

**Issue by rickgrubin** [JCSDA-internal/jedi-stack-old#171]
## Description

Update build script for FMS to accommodate GNU Fortran v10.x

This PR borrows the code idiom from [jedi-stack PR #168](https://github.com/JCSDA/jedi-stack/pull/168) to determine if the Fortran compiler specified for building is GNU Fortran v10.x.

## Dependencies

No dependencies; related to [jedi-stack PR #160](https://github.com/JCSDA/jedi-stack/pull/160) `add FMS to the stack`

## Impact

No impact to other repositories or test data.

## Done

- Build stack / install module as appropriate where GNU Fortran v10.x is available
  - macOS: clang v11.0.3 and GNU 10.2.0, mpich-3.3.2 and openmpi-4.0.3
  - Orion: GNU v10.2.0 compiler suite, openmpi-4.0.4

n.b.: The only place we're building against GNU Fortran v10.x are local hosts (macOSX) and Orion (modules are available, but not advertised).

**Comment by mmiesch** [comment]
Issue moved to [JCSDA-internal/jedi-stack #26](https://github.com/JCSDA-internal/jedi-stack/issues/26) via [**ZenHub**](https://www.zenhub.com/)
