### ISSUE TITLE
`discover` modules `jedi-python` distribution cannot install `cartopy`

### ISSUE THREAD

**Issue by markjolah** [JCSDA-internal/jedi-stack-old#176]
I ran into an issue with the new `jedi-python` module, where I can't install `cartopy` which is a required dependency for the ioda plotting and NRT workflow.  I am however able to install and get everything working with the `python/GEOSpyD` module.  To get it all working for the GEOS workflow, I'm going to have the rapids discover config unload the `jedi-python` and load `python/GEOSpyD`.

What was the original blocker with the `python/GEOSpyD` module?  Maybe it will be easier to solve those issues than manage a whole different python?

I'm looping in @danholdaway to see how he is using python on Discover?  I'd like to get Rapids working well with whatever the common practice is there.

Here's a sample of the error.  I think you need `proj` and `geos` (not the model) packages, which is a pain since it seems the `python/GEOSpyD` already has them?

```
$ module load jedi-python
$ pip install --user cartopy
....
creating build/temp.linux-x86_64-3.8/lib/cartopy
  mpicc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1 -I/discover/swdev/jcsda/modules/miniconda3/include -I./lib/cartopy -I/home/molah/.local/lib/python3.8/site-packages/numpy/core/include -I/usr/local/other/python/GEOSpyD/4.8.3_py3.8/2020-08-11/include -I/discover/swdev/jcsda/modules/miniconda3/include/python3.8 -c lib/cartopy/trace.cpp -o build/temp.linux-x86_64-3.8/lib/cartopy/trace.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  lib/cartopy/trace.cpp: In function ‘void __pyx_f_7cartopy_5trace__project_segment(GEOSContextHandle_t, const GEOSCoordSequence*, unsigned int, unsigned int, __pyx_obj_7cartopy_5trace_Interpolator*, const GEOSPreparedGeometry*, double, __pyx_obj_7cartopy_5trace_LineAccumulator*)’:
  lib/cartopy/trace.cpp:6362:37: warning: ‘__pyx_v_t_max’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   6362 |       __pyx_t_2 = PyFloat_FromDouble(__pyx_v_t_max); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 539, __pyx_L1_error)
        |                   ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
  lib/cartopy/trace.cpp:6360:37: warning: ‘__pyx_v_t_min’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   6360 |       __pyx_t_3 = PyFloat_FromDouble(__pyx_v_t_min); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 539, __pyx_L1_error)
        |                   ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
  mpicxx -pthread -shared -B /discover/swdev/jcsda/modules/miniconda3/compiler_compat -L/discover/swdev/jcsda/modules/miniconda3/lib -Wl,-rpath=/discover/swdev/jcsda/modules/miniconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/lib/cartopy/trace.o -L/discover/swdev/jcsda/modules/miniconda3/lib -L/usr/local/other/python/GEOSpyD/4.8.3_py3.8/2020-08-11/lib -Wl,-R/discover/swdev/jcsda/modules/miniconda3/lib -lproj -lgeos_c -o build/lib.linux-x86_64-3.8/cartopy/trace.cpython-38-x86_64-linux-gnu.so
  building 'cartopy._crs' extension
  mpicc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1 -I/discover/swdev/jcsda/modules/miniconda3/include -I/home/molah/.local/lib/python3.8/site-packages/numpy/core/include -I/discover/swdev/jcsda/modules/miniconda3/include/python3.8 -c lib/cartopy/_crs.c -o build/temp.linux-x86_64-3.8/lib/cartopy/_crs.o
  lib/cartopy/_crs.c:637:10: fatal error: proj_api.h: No such file or directory
    637 | #include "proj_api.h"
        |          ^~~~~~~~~~~~
  compilation terminated.
  error: command 'mpicc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cartopy

```

**Comment by mmiesch** [comment]
>What was the original blocker with the python/GEOSpyD module? Maybe it will be easier to solve those issues than manage a whole different python?

The blocker was that loading the `python/GEOSpyD` module loaded its own version of netcdf, which was conflicting with the netcdf in jedi-stack and causing [build failures](https://github.com/JCSDA/jedi-stack/issues/161).  The jedi-python module uses miniconda so it should be straightforward to install cartopy and other things and make them available to users.  But, I'm swamped with other things - I probably won't be able to get to that anytime soon.

**Comment by mmiesch** [comment]
In the meantime, it might work to load jedi-python for compiling bundles and then swap it out for python/GESOpyD when you run the workflow and generate plots (as long as the dual netcdf versions don't conflict at run time).  Maybe this is essentially what you're already doing?

**Comment by danholdaway** [comment]
@markjolah I use my own install of Anaconda that is located here: /gpfsm/dnb31/drholdaw/Programs/anaconda3/bin/python I can install and generate plots with ioda-plots so it should work for what we need. I can install additional packages if you need.

**Comment by markjolah** [comment]
OK.  Sorry for the confusion.  I definitely confirmed the NetCDF versioning issue.  That is frustrating.  I'm testing if i can run without GEOSpyD loaded.

**Comment by mmiesch** [comment]
Issue moved to [JCSDA-internal/jedi-stack #30](https://github.com/JCSDA-internal/jedi-stack/issues/30) via [**ZenHub**](https://www.zenhub.com/)
