### ISSUE TITLE
`discover` modules `intel-impi` random segmentation faults

### ISSUE THREAD

**Issue by markjolah** [JCSDA-internal/jedi-stack-old#179]
I've been running into this issue repeatedly, where the intel-2020 series `mpiifort` is SegFaulting on some compilations.  It seems to be intermittent, and moving from file to file.  Hard to track down, but definitely reoccurring.  I've resorted to building `intel-impi` with `-j1`, but I'm still seeing failures in that mode.  Some failures have been in `atlas`, but the most recent failure is now also in `crtm`
```
[ 38%] Building Fortran object crtm/test/CMakeFiles/test_forward_test_SSU.dir/mains/regression/forward/test_SSU/test_SSU.f90.o
/usr/local/intel/2020/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpiifort: line 709: 29940 Segmentation fault      /usr/local/intel/2020/compilers_and_libraries_2020.0.166/linux/bin/intel64/ifort -DNDEBUG -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/crtm/libsrc -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/module/crtm/Intel/19.1.0.20191121 -I/discover/swdev/jcsda/modules/intel-19.1.0.166/impi-19.1.0.166/netcdf/4.7.4/include '-assume' 'byterecl' '-O3' '-ip' '-unroll' '-inline' '-no-heap-arrays' '-assume' 'byterecl' '-module' '../../module' '-fPIE' '-qopenmp' -c '/gpfsm/dnb55/molah/rapids/build/jcsda/develop/crtm/test/mains/regression/forward/test_SSU/test_SSU.f90' -o 'CMakeFiles/test_forward_test_SSU.dir/mains/regression/forward/test_SSU/test_SSU.f90.o' -I/usr/local/intel/2020/compilers_and_libraries_2020.0.166/linux/mpi/intel64/include -I/usr/local/intel/2020/compilers_and_libraries_2020.0.166/linux/mpi/intel64/include
crtm/test/CMakeFiles/test_forward_test_SSU.dir/build.make:82: recipe for target 'crtm/test/CMakeFiles/test_forward_test_SSU.dir/mains/regression/forward/test_SSU/test_SSU.f90.o' failed
make[2]: *** [crtm/test/CMakeFiles/test_forward_test_SSU.dir/mains/regression/forward/test_SSU/test_SSU.f90.o] Error 139
```

Manually Re-running the failed compilation appears to succeed, and I can't reproduce the failure.  I am not sure how to debug this, but I'm going on a hunch that maybe the stack size ulimit is getting exceeded which could be causing a segfault.  I noticed the default `ulimit -s` is `8192`, I will see if maybe un-restricting that will cause the errors to vanish.  I'll open this issue to track any other examples of segfaults.

**Comment by mmiesch** [comment]
Yes - I have had some success in compiling atlas serially and then restarting the compilation with `-j4` or `-j8` after it gets through atlas.  I haven't noticed the crtm issue.

**Comment by mmiesch** [comment]
Issue moved to [JCSDA-internal/jedi-stack #31](https://github.com/JCSDA-internal/jedi-stack/issues/31) via [**ZenHub**](https://www.zenhub.com/)
